#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angajati
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Coffee_Shopp")]
	public partial class CoffeeShopDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAngajat(Angajat instance);
    partial void UpdateAngajat(Angajat instance);
    partial void DeleteAngajat(Angajat instance);
    partial void InsertCafele(Cafele instance);
    partial void UpdateCafele(Cafele instance);
    partial void DeleteCafele(Cafele instance);
    partial void InsertComenzi(Comenzi instance);
    partial void UpdateComenzi(Comenzi instance);
    partial void DeleteComenzi(Comenzi instance);
    partial void InsertDetaliiComenzi(DetaliiComenzi instance);
    partial void UpdateDetaliiComenzi(DetaliiComenzi instance);
    partial void DeleteDetaliiComenzi(DetaliiComenzi instance);
    partial void InsertMese(Mese instance);
    partial void UpdateMese(Mese instance);
    partial void DeleteMese(Mese instance);
    partial void InsertProduse(Produse instance);
    partial void UpdateProduse(Produse instance);
    partial void DeleteProduse(Produse instance);
    partial void InsertRezervari(Rezervari instance);
    partial void UpdateRezervari(Rezervari instance);
    partial void DeleteRezervari(Rezervari instance);
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    #endregion
		
		public CoffeeShopDataContext() : 
				base(global::Angajati.Properties.Settings.Default.Coffee_ShoppConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CoffeeShopDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoffeeShopDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoffeeShopDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoffeeShopDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Angajat> Angajats
		{
			get
			{
				return this.GetTable<Angajat>();
			}
		}
		
		public System.Data.Linq.Table<Cafele> Cafeles
		{
			get
			{
				return this.GetTable<Cafele>();
			}
		}
		
		public System.Data.Linq.Table<Comenzi> Comenzis
		{
			get
			{
				return this.GetTable<Comenzi>();
			}
		}
		
		public System.Data.Linq.Table<DetaliiComenzi> DetaliiComenzis
		{
			get
			{
				return this.GetTable<DetaliiComenzi>();
			}
		}
		
		public System.Data.Linq.Table<Mese> Meses
		{
			get
			{
				return this.GetTable<Mese>();
			}
		}
		
		public System.Data.Linq.Table<Produse> Produses
		{
			get
			{
				return this.GetTable<Produse>();
			}
		}
		
		public System.Data.Linq.Table<Rezervari> Rezervaris
		{
			get
			{
				return this.GetTable<Rezervari>();
			}
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetClientNameByOrderId")]
		public ISingleResult<GetClientNameByOrderIdResult> GetClientNameByOrderId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDComanda", DbType="Int")] System.Nullable<int> iDComanda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDComanda);
			return ((ISingleResult<GetClientNameByOrderIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetClientNameByReservationId")]
		public ISingleResult<GetClientNameByReservationIdResult> GetClientNameByReservationId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRezervare", DbType="Int")] System.Nullable<int> iDRezervare)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRezervare);
			return ((ISingleResult<GetClientNameByReservationIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEmployeeIdByEmail")]
		public ISingleResult<GetEmployeeIdByEmailResult> GetEmployeeIdByEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(30)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<GetEmployeeIdByEmailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNrLocuriByIdRezervare")]
		public ISingleResult<GetNrLocuriByIdRezervareResult> GetNrLocuriByIdRezervare([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRezervare", DbType="Int")] System.Nullable<int> iDRezervare)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRezervare);
			return ((ISingleResult<GetNrLocuriByIdRezervareResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNumeByEmail")]
		public ISingleResult<GetNumeByEmailResult> GetNumeByEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(255)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<GetNumeByEmailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNumePrenumeByEmail")]
		public ISingleResult<GetNumePrenumeByEmailResult> GetNumePrenumeByEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(255)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<GetNumePrenumeByEmailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPrenumeByEmail")]
		public ISingleResult<GetPrenumeByEmailResult> GetPrenumeByEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(255)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<GetPrenumeByEmailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRolByEmail")]
		public ISingleResult<GetRolByEmailResult> GetRolByEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(255)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<GetRolByEmailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateIDAngajatByIdComanda")]
		public int UpdateIDAngajatByIdComanda([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDAngajat", DbType="Int")] System.Nullable<int> iDAngajat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDComanda", DbType="Int")] System.Nullable<int> iDComanda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDAngajat, iDComanda);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateIDAngajatByIdRezervare")]
		public int UpdateIDAngajatByIdRezervare([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDAngajat", DbType="Int")] System.Nullable<int> iDAngajat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRezervare", DbType="Int")] System.Nullable<int> iDRezervare)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDAngajat, iDRezervare);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdaugaLaStoc")]
		public int AdaugaLaStoc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantitateAdaugata", DbType="Int")] System.Nullable<int> cantitateAdaugata, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenumireProdus", DbType="NVarChar(20)")] string denumireProdus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cantitateAdaugata, denumireProdus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ScadePuncte")]
		public int ScadePuncte([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NrPuncte", DbType="Int")] System.Nullable<int> nrPuncte, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailClient", DbType="NVarChar(20)")] string emailClient)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nrPuncte, emailClient);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdaugaPuncte")]
		public int AdaugaPuncte([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NrPuncte", DbType="Int")] System.Nullable<int> nrPuncte, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailClient", DbType="NVarChar(20)")] string emailClient)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nrPuncte, emailClient);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VerificaAdministrator")]
		public int VerificaAdministrator([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDAngajat", DbType="Int")] System.Nullable<int> iDAngajat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDAngajat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VerificaAdministratorPeEmail")]
		public int VerificaAdministratorPeEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(30)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Angajat")]
	public partial class Angajat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDAngajat;
		
		private string _Nume;
		
		private string _Prenume;
		
		private System.Nullable<System.DateTime> _DataNastere;
		
		private string _Username;
		
		private string _Email;
		
		private string _Parola;
		
		private string _Rol;
		
		private string _NrTelefon;
		
		private EntitySet<Comenzi> _Comenzis;
		
		private EntitySet<Rezervari> _Rezervaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDAngajatChanging(int value);
    partial void OnIDAngajatChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnDataNastereChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNastereChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnParolaChanging(string value);
    partial void OnParolaChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    partial void OnNrTelefonChanging(string value);
    partial void OnNrTelefonChanged();
    #endregion
		
		public Angajat()
		{
			this._Comenzis = new EntitySet<Comenzi>(new Action<Comenzi>(this.attach_Comenzis), new Action<Comenzi>(this.detach_Comenzis));
			this._Rezervaris = new EntitySet<Rezervari>(new Action<Rezervari>(this.attach_Rezervaris), new Action<Rezervari>(this.detach_Rezervaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAngajat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDAngajat
		{
			get
			{
				return this._IDAngajat;
			}
			set
			{
				if ((this._IDAngajat != value))
				{
					this.OnIDAngajatChanging(value);
					this.SendPropertyChanging();
					this._IDAngajat = value;
					this.SendPropertyChanged("IDAngajat");
					this.OnIDAngajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNastere", DbType="Date")]
		public System.Nullable<System.DateTime> DataNastere
		{
			get
			{
				return this._DataNastere;
			}
			set
			{
				if ((this._DataNastere != value))
				{
					this.OnDataNastereChanging(value);
					this.SendPropertyChanging();
					this._DataNastere = value;
					this.SendPropertyChanged("DataNastere");
					this.OnDataNastereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(20)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parola", DbType="VarChar(517)")]
		public string Parola
		{
			get
			{
				return this._Parola;
			}
			set
			{
				if ((this._Parola != value))
				{
					this.OnParolaChanging(value);
					this.SendPropertyChanging();
					this._Parola = value;
					this.SendPropertyChanged("Parola");
					this.OnParolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="NVarChar(8)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrTelefon", DbType="NVarChar(10)")]
		public string NrTelefon
		{
			get
			{
				return this._NrTelefon;
			}
			set
			{
				if ((this._NrTelefon != value))
				{
					this.OnNrTelefonChanging(value);
					this.SendPropertyChanging();
					this._NrTelefon = value;
					this.SendPropertyChanged("NrTelefon");
					this.OnNrTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajat_Comenzi", Storage="_Comenzis", ThisKey="IDAngajat", OtherKey="IDAngajat")]
		public EntitySet<Comenzi> Comenzis
		{
			get
			{
				return this._Comenzis;
			}
			set
			{
				this._Comenzis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajat_Rezervari", Storage="_Rezervaris", ThisKey="IDAngajat", OtherKey="IDAngajat")]
		public EntitySet<Rezervari> Rezervaris
		{
			get
			{
				return this._Rezervaris;
			}
			set
			{
				this._Rezervaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comenzis(Comenzi entity)
		{
			this.SendPropertyChanging();
			entity.Angajat = this;
		}
		
		private void detach_Comenzis(Comenzi entity)
		{
			this.SendPropertyChanging();
			entity.Angajat = null;
		}
		
		private void attach_Rezervaris(Rezervari entity)
		{
			this.SendPropertyChanging();
			entity.Angajat = this;
		}
		
		private void detach_Rezervaris(Rezervari entity)
		{
			this.SendPropertyChanging();
			entity.Angajat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cafele")]
	public partial class Cafele : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDProdus;
		
		private string _Denumire;
		
		private System.Nullable<int> _ShoturiEspresso;
		
		private string _TipLapte;
		
		private string _Sirop;
		
		private System.Nullable<int> _Frisca;
		
		private System.Nullable<int> _Pret;
		
		private EntitySet<DetaliiComenzi> _DetaliiComenzis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDProdusChanging(int value);
    partial void OnIDProdusChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    partial void OnShoturiEspressoChanging(System.Nullable<int> value);
    partial void OnShoturiEspressoChanged();
    partial void OnTipLapteChanging(string value);
    partial void OnTipLapteChanged();
    partial void OnSiropChanging(string value);
    partial void OnSiropChanged();
    partial void OnFriscaChanging(System.Nullable<int> value);
    partial void OnFriscaChanged();
    partial void OnPretChanging(System.Nullable<int> value);
    partial void OnPretChanged();
    #endregion
		
		public Cafele()
		{
			this._DetaliiComenzis = new EntitySet<DetaliiComenzi>(new Action<DetaliiComenzi>(this.attach_DetaliiComenzis), new Action<DetaliiComenzi>(this.detach_DetaliiComenzis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDProdus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDProdus
		{
			get
			{
				return this._IDProdus;
			}
			set
			{
				if ((this._IDProdus != value))
				{
					this.OnIDProdusChanging(value);
					this.SendPropertyChanging();
					this._IDProdus = value;
					this.SendPropertyChanged("IDProdus");
					this.OnIDProdusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="NVarChar(10)")]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoturiEspresso", DbType="Int")]
		public System.Nullable<int> ShoturiEspresso
		{
			get
			{
				return this._ShoturiEspresso;
			}
			set
			{
				if ((this._ShoturiEspresso != value))
				{
					this.OnShoturiEspressoChanging(value);
					this.SendPropertyChanging();
					this._ShoturiEspresso = value;
					this.SendPropertyChanged("ShoturiEspresso");
					this.OnShoturiEspressoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipLapte", DbType="NVarChar(50)")]
		public string TipLapte
		{
			get
			{
				return this._TipLapte;
			}
			set
			{
				if ((this._TipLapte != value))
				{
					this.OnTipLapteChanging(value);
					this.SendPropertyChanging();
					this._TipLapte = value;
					this.SendPropertyChanged("TipLapte");
					this.OnTipLapteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sirop", DbType="NVarChar(50)")]
		public string Sirop
		{
			get
			{
				return this._Sirop;
			}
			set
			{
				if ((this._Sirop != value))
				{
					this.OnSiropChanging(value);
					this.SendPropertyChanging();
					this._Sirop = value;
					this.SendPropertyChanged("Sirop");
					this.OnSiropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frisca", DbType="Int")]
		public System.Nullable<int> Frisca
		{
			get
			{
				return this._Frisca;
			}
			set
			{
				if ((this._Frisca != value))
				{
					this.OnFriscaChanging(value);
					this.SendPropertyChanging();
					this._Frisca = value;
					this.SendPropertyChanged("Frisca");
					this.OnFriscaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret", DbType="Int")]
		public System.Nullable<int> Pret
		{
			get
			{
				return this._Pret;
			}
			set
			{
				if ((this._Pret != value))
				{
					this.OnPretChanging(value);
					this.SendPropertyChanging();
					this._Pret = value;
					this.SendPropertyChanged("Pret");
					this.OnPretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cafele_DetaliiComenzi", Storage="_DetaliiComenzis", ThisKey="IDProdus", OtherKey="IDCafea")]
		public EntitySet<DetaliiComenzi> DetaliiComenzis
		{
			get
			{
				return this._DetaliiComenzis;
			}
			set
			{
				this._DetaliiComenzis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetaliiComenzis(DetaliiComenzi entity)
		{
			this.SendPropertyChanging();
			entity.Cafele = this;
		}
		
		private void detach_DetaliiComenzis(DetaliiComenzi entity)
		{
			this.SendPropertyChanging();
			entity.Cafele = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comenzi")]
	public partial class Comenzi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDComanda;
		
		private System.Nullable<int> _IDClient;
		
		private System.Nullable<int> _IDAngajat;
		
		private System.Nullable<System.DateTime> _DataComanda;
		
		private System.Nullable<int> _ModalitatePlata;
		
		private System.Nullable<decimal> _Pret;
		
		private EntitySet<DetaliiComenzi> _DetaliiComenzis;
		
		private EntityRef<Angajat> _Angajat;
		
		private EntityRef<Client> _Client;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDComandaChanging(int value);
    partial void OnIDComandaChanged();
    partial void OnIDClientChanging(System.Nullable<int> value);
    partial void OnIDClientChanged();
    partial void OnIDAngajatChanging(System.Nullable<int> value);
    partial void OnIDAngajatChanged();
    partial void OnDataComandaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataComandaChanged();
    partial void OnModalitatePlataChanging(System.Nullable<int> value);
    partial void OnModalitatePlataChanged();
    partial void OnPretChanging(System.Nullable<decimal> value);
    partial void OnPretChanged();
    #endregion
		
		public Comenzi()
		{
			this._DetaliiComenzis = new EntitySet<DetaliiComenzi>(new Action<DetaliiComenzi>(this.attach_DetaliiComenzis), new Action<DetaliiComenzi>(this.detach_DetaliiComenzis));
			this._Angajat = default(EntityRef<Angajat>);
			this._Client = default(EntityRef<Client>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDComanda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDComanda
		{
			get
			{
				return this._IDComanda;
			}
			set
			{
				if ((this._IDComanda != value))
				{
					this.OnIDComandaChanging(value);
					this.SendPropertyChanging();
					this._IDComanda = value;
					this.SendPropertyChanged("IDComanda");
					this.OnIDComandaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDClient", DbType="Int")]
		public System.Nullable<int> IDClient
		{
			get
			{
				return this._IDClient;
			}
			set
			{
				if ((this._IDClient != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDClientChanging(value);
					this.SendPropertyChanging();
					this._IDClient = value;
					this.SendPropertyChanged("IDClient");
					this.OnIDClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAngajat", DbType="Int")]
		public System.Nullable<int> IDAngajat
		{
			get
			{
				return this._IDAngajat;
			}
			set
			{
				if ((this._IDAngajat != value))
				{
					if (this._Angajat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDAngajatChanging(value);
					this.SendPropertyChanging();
					this._IDAngajat = value;
					this.SendPropertyChanged("IDAngajat");
					this.OnIDAngajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataComanda", DbType="Date")]
		public System.Nullable<System.DateTime> DataComanda
		{
			get
			{
				return this._DataComanda;
			}
			set
			{
				if ((this._DataComanda != value))
				{
					this.OnDataComandaChanging(value);
					this.SendPropertyChanging();
					this._DataComanda = value;
					this.SendPropertyChanged("DataComanda");
					this.OnDataComandaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModalitatePlata", DbType="Int")]
		public System.Nullable<int> ModalitatePlata
		{
			get
			{
				return this._ModalitatePlata;
			}
			set
			{
				if ((this._ModalitatePlata != value))
				{
					this.OnModalitatePlataChanging(value);
					this.SendPropertyChanging();
					this._ModalitatePlata = value;
					this.SendPropertyChanged("ModalitatePlata");
					this.OnModalitatePlataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Pret
		{
			get
			{
				return this._Pret;
			}
			set
			{
				if ((this._Pret != value))
				{
					this.OnPretChanging(value);
					this.SendPropertyChanging();
					this._Pret = value;
					this.SendPropertyChanged("Pret");
					this.OnPretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comenzi_DetaliiComenzi", Storage="_DetaliiComenzis", ThisKey="IDComanda", OtherKey="IDComanda")]
		public EntitySet<DetaliiComenzi> DetaliiComenzis
		{
			get
			{
				return this._DetaliiComenzis;
			}
			set
			{
				this._DetaliiComenzis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajat_Comenzi", Storage="_Angajat", ThisKey="IDAngajat", OtherKey="IDAngajat", IsForeignKey=true)]
		public Angajat Angajat
		{
			get
			{
				return this._Angajat.Entity;
			}
			set
			{
				Angajat previousValue = this._Angajat.Entity;
				if (((previousValue != value) 
							|| (this._Angajat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Angajat.Entity = null;
						previousValue.Comenzis.Remove(this);
					}
					this._Angajat.Entity = value;
					if ((value != null))
					{
						value.Comenzis.Add(this);
						this._IDAngajat = value.IDAngajat;
					}
					else
					{
						this._IDAngajat = default(Nullable<int>);
					}
					this.SendPropertyChanged("Angajat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Comenzi", Storage="_Client", ThisKey="IDClient", OtherKey="IDClient", IsForeignKey=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.Comenzis.Remove(this);
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.Comenzis.Add(this);
						this._IDClient = value.IDClient;
					}
					else
					{
						this._IDClient = default(Nullable<int>);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetaliiComenzis(DetaliiComenzi entity)
		{
			this.SendPropertyChanging();
			entity.Comenzi = this;
		}
		
		private void detach_DetaliiComenzis(DetaliiComenzi entity)
		{
			this.SendPropertyChanging();
			entity.Comenzi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetaliiComenzi")]
	public partial class DetaliiComenzi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDetaliiComanda;
		
		private System.Nullable<int> _IDComanda;
		
		private System.Nullable<int> _IDCafea;
		
		private System.Nullable<int> _IDMasa;
		
		private System.Nullable<int> _Cantitate;
		
		private System.Nullable<int> _NrPersoane;
		
		private EntityRef<Cafele> _Cafele;
		
		private EntityRef<Comenzi> _Comenzi;
		
		private EntityRef<Mese> _Mese;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDetaliiComandaChanging(int value);
    partial void OnIDDetaliiComandaChanged();
    partial void OnIDComandaChanging(System.Nullable<int> value);
    partial void OnIDComandaChanged();
    partial void OnIDCafeaChanging(System.Nullable<int> value);
    partial void OnIDCafeaChanged();
    partial void OnIDMasaChanging(System.Nullable<int> value);
    partial void OnIDMasaChanged();
    partial void OnCantitateChanging(System.Nullable<int> value);
    partial void OnCantitateChanged();
    partial void OnNrPersoaneChanging(System.Nullable<int> value);
    partial void OnNrPersoaneChanged();
    #endregion
		
		public DetaliiComenzi()
		{
			this._Cafele = default(EntityRef<Cafele>);
			this._Comenzi = default(EntityRef<Comenzi>);
			this._Mese = default(EntityRef<Mese>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDetaliiComanda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDetaliiComanda
		{
			get
			{
				return this._IDDetaliiComanda;
			}
			set
			{
				if ((this._IDDetaliiComanda != value))
				{
					this.OnIDDetaliiComandaChanging(value);
					this.SendPropertyChanging();
					this._IDDetaliiComanda = value;
					this.SendPropertyChanged("IDDetaliiComanda");
					this.OnIDDetaliiComandaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDComanda", DbType="Int")]
		public System.Nullable<int> IDComanda
		{
			get
			{
				return this._IDComanda;
			}
			set
			{
				if ((this._IDComanda != value))
				{
					if (this._Comenzi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDComandaChanging(value);
					this.SendPropertyChanging();
					this._IDComanda = value;
					this.SendPropertyChanged("IDComanda");
					this.OnIDComandaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCafea", DbType="Int")]
		public System.Nullable<int> IDCafea
		{
			get
			{
				return this._IDCafea;
			}
			set
			{
				if ((this._IDCafea != value))
				{
					if (this._Cafele.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCafeaChanging(value);
					this.SendPropertyChanging();
					this._IDCafea = value;
					this.SendPropertyChanged("IDCafea");
					this.OnIDCafeaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMasa", DbType="Int")]
		public System.Nullable<int> IDMasa
		{
			get
			{
				return this._IDMasa;
			}
			set
			{
				if ((this._IDMasa != value))
				{
					if (this._Mese.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDMasaChanging(value);
					this.SendPropertyChanging();
					this._IDMasa = value;
					this.SendPropertyChanged("IDMasa");
					this.OnIDMasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantitate", DbType="Int")]
		public System.Nullable<int> Cantitate
		{
			get
			{
				return this._Cantitate;
			}
			set
			{
				if ((this._Cantitate != value))
				{
					this.OnCantitateChanging(value);
					this.SendPropertyChanging();
					this._Cantitate = value;
					this.SendPropertyChanged("Cantitate");
					this.OnCantitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrPersoane", DbType="Int")]
		public System.Nullable<int> NrPersoane
		{
			get
			{
				return this._NrPersoane;
			}
			set
			{
				if ((this._NrPersoane != value))
				{
					this.OnNrPersoaneChanging(value);
					this.SendPropertyChanging();
					this._NrPersoane = value;
					this.SendPropertyChanged("NrPersoane");
					this.OnNrPersoaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cafele_DetaliiComenzi", Storage="_Cafele", ThisKey="IDCafea", OtherKey="IDProdus", IsForeignKey=true)]
		public Cafele Cafele
		{
			get
			{
				return this._Cafele.Entity;
			}
			set
			{
				Cafele previousValue = this._Cafele.Entity;
				if (((previousValue != value) 
							|| (this._Cafele.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cafele.Entity = null;
						previousValue.DetaliiComenzis.Remove(this);
					}
					this._Cafele.Entity = value;
					if ((value != null))
					{
						value.DetaliiComenzis.Add(this);
						this._IDCafea = value.IDProdus;
					}
					else
					{
						this._IDCafea = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cafele");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Comenzi_DetaliiComenzi", Storage="_Comenzi", ThisKey="IDComanda", OtherKey="IDComanda", IsForeignKey=true)]
		public Comenzi Comenzi
		{
			get
			{
				return this._Comenzi.Entity;
			}
			set
			{
				Comenzi previousValue = this._Comenzi.Entity;
				if (((previousValue != value) 
							|| (this._Comenzi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Comenzi.Entity = null;
						previousValue.DetaliiComenzis.Remove(this);
					}
					this._Comenzi.Entity = value;
					if ((value != null))
					{
						value.DetaliiComenzis.Add(this);
						this._IDComanda = value.IDComanda;
					}
					else
					{
						this._IDComanda = default(Nullable<int>);
					}
					this.SendPropertyChanged("Comenzi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mese_DetaliiComenzi", Storage="_Mese", ThisKey="IDMasa", OtherKey="IDMasa", IsForeignKey=true)]
		public Mese Mese
		{
			get
			{
				return this._Mese.Entity;
			}
			set
			{
				Mese previousValue = this._Mese.Entity;
				if (((previousValue != value) 
							|| (this._Mese.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mese.Entity = null;
						previousValue.DetaliiComenzis.Remove(this);
					}
					this._Mese.Entity = value;
					if ((value != null))
					{
						value.DetaliiComenzis.Add(this);
						this._IDMasa = value.IDMasa;
					}
					else
					{
						this._IDMasa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Mese");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mese")]
	public partial class Mese : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDMasa;
		
		private System.Nullable<System.DateTime> _DataRezervare;
		
		private System.Nullable<int> _NumarLocuriDisponibile;
		
		private string _OraRezervare;
		
		private EntitySet<DetaliiComenzi> _DetaliiComenzis;
		
		private EntitySet<Rezervari> _Rezervaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMasaChanging(int value);
    partial void OnIDMasaChanged();
    partial void OnDataRezervareChanging(System.Nullable<System.DateTime> value);
    partial void OnDataRezervareChanged();
    partial void OnNumarLocuriDisponibileChanging(System.Nullable<int> value);
    partial void OnNumarLocuriDisponibileChanged();
    partial void OnOraRezervareChanging(string value);
    partial void OnOraRezervareChanged();
    #endregion
		
		public Mese()
		{
			this._DetaliiComenzis = new EntitySet<DetaliiComenzi>(new Action<DetaliiComenzi>(this.attach_DetaliiComenzis), new Action<DetaliiComenzi>(this.detach_DetaliiComenzis));
			this._Rezervaris = new EntitySet<Rezervari>(new Action<Rezervari>(this.attach_Rezervaris), new Action<Rezervari>(this.detach_Rezervaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMasa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDMasa
		{
			get
			{
				return this._IDMasa;
			}
			set
			{
				if ((this._IDMasa != value))
				{
					this.OnIDMasaChanging(value);
					this.SendPropertyChanging();
					this._IDMasa = value;
					this.SendPropertyChanged("IDMasa");
					this.OnIDMasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRezervare", DbType="Date")]
		public System.Nullable<System.DateTime> DataRezervare
		{
			get
			{
				return this._DataRezervare;
			}
			set
			{
				if ((this._DataRezervare != value))
				{
					this.OnDataRezervareChanging(value);
					this.SendPropertyChanging();
					this._DataRezervare = value;
					this.SendPropertyChanged("DataRezervare");
					this.OnDataRezervareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumarLocuriDisponibile", DbType="Int")]
		public System.Nullable<int> NumarLocuriDisponibile
		{
			get
			{
				return this._NumarLocuriDisponibile;
			}
			set
			{
				if ((this._NumarLocuriDisponibile != value))
				{
					this.OnNumarLocuriDisponibileChanging(value);
					this.SendPropertyChanging();
					this._NumarLocuriDisponibile = value;
					this.SendPropertyChanged("NumarLocuriDisponibile");
					this.OnNumarLocuriDisponibileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OraRezervare", DbType="NVarChar(6)")]
		public string OraRezervare
		{
			get
			{
				return this._OraRezervare;
			}
			set
			{
				if ((this._OraRezervare != value))
				{
					this.OnOraRezervareChanging(value);
					this.SendPropertyChanging();
					this._OraRezervare = value;
					this.SendPropertyChanged("OraRezervare");
					this.OnOraRezervareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mese_DetaliiComenzi", Storage="_DetaliiComenzis", ThisKey="IDMasa", OtherKey="IDMasa")]
		public EntitySet<DetaliiComenzi> DetaliiComenzis
		{
			get
			{
				return this._DetaliiComenzis;
			}
			set
			{
				this._DetaliiComenzis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mese_Rezervari", Storage="_Rezervaris", ThisKey="IDMasa", OtherKey="IDMasa")]
		public EntitySet<Rezervari> Rezervaris
		{
			get
			{
				return this._Rezervaris;
			}
			set
			{
				this._Rezervaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetaliiComenzis(DetaliiComenzi entity)
		{
			this.SendPropertyChanging();
			entity.Mese = this;
		}
		
		private void detach_DetaliiComenzis(DetaliiComenzi entity)
		{
			this.SendPropertyChanging();
			entity.Mese = null;
		}
		
		private void attach_Rezervaris(Rezervari entity)
		{
			this.SendPropertyChanging();
			entity.Mese = this;
		}
		
		private void detach_Rezervaris(Rezervari entity)
		{
			this.SendPropertyChanging();
			entity.Mese = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produse")]
	public partial class Produse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDProdus;
		
		private string _Denumire;
		
		private System.Nullable<int> _Stoc;
		
		private System.Nullable<decimal> _Pret;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDProdusChanging(int value);
    partial void OnIDProdusChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    partial void OnStocChanging(System.Nullable<int> value);
    partial void OnStocChanged();
    partial void OnPretChanging(System.Nullable<decimal> value);
    partial void OnPretChanged();
    #endregion
		
		public Produse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDProdus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDProdus
		{
			get
			{
				return this._IDProdus;
			}
			set
			{
				if ((this._IDProdus != value))
				{
					this.OnIDProdusChanging(value);
					this.SendPropertyChanging();
					this._IDProdus = value;
					this.SendPropertyChanged("IDProdus");
					this.OnIDProdusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="NVarChar(20)")]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stoc", DbType="Int")]
		public System.Nullable<int> Stoc
		{
			get
			{
				return this._Stoc;
			}
			set
			{
				if ((this._Stoc != value))
				{
					this.OnStocChanging(value);
					this.SendPropertyChanging();
					this._Stoc = value;
					this.SendPropertyChanged("Stoc");
					this.OnStocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Pret
		{
			get
			{
				return this._Pret;
			}
			set
			{
				if ((this._Pret != value))
				{
					this.OnPretChanging(value);
					this.SendPropertyChanging();
					this._Pret = value;
					this.SendPropertyChanged("Pret");
					this.OnPretChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rezervari")]
	public partial class Rezervari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDRezervare;
		
		private System.Nullable<int> _IDClient;
		
		private System.Nullable<int> _IDAngajat;
		
		private System.Nullable<int> _IDMasa;
		
		private System.Nullable<System.DateTime> _DataRezervare;
		
		private System.Nullable<int> _NrLocuri;
		
		private string _Ora;
		
		private EntityRef<Angajat> _Angajat;
		
		private EntityRef<Mese> _Mese;
		
		private EntityRef<Client> _Client;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDRezervareChanging(int value);
    partial void OnIDRezervareChanged();
    partial void OnIDClientChanging(System.Nullable<int> value);
    partial void OnIDClientChanged();
    partial void OnIDAngajatChanging(System.Nullable<int> value);
    partial void OnIDAngajatChanged();
    partial void OnIDMasaChanging(System.Nullable<int> value);
    partial void OnIDMasaChanged();
    partial void OnDataRezervareChanging(System.Nullable<System.DateTime> value);
    partial void OnDataRezervareChanged();
    partial void OnNrLocuriChanging(System.Nullable<int> value);
    partial void OnNrLocuriChanged();
    partial void OnOraChanging(string value);
    partial void OnOraChanged();
    #endregion
		
		public Rezervari()
		{
			this._Angajat = default(EntityRef<Angajat>);
			this._Mese = default(EntityRef<Mese>);
			this._Client = default(EntityRef<Client>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRezervare", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDRezervare
		{
			get
			{
				return this._IDRezervare;
			}
			set
			{
				if ((this._IDRezervare != value))
				{
					this.OnIDRezervareChanging(value);
					this.SendPropertyChanging();
					this._IDRezervare = value;
					this.SendPropertyChanged("IDRezervare");
					this.OnIDRezervareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDClient", DbType="Int")]
		public System.Nullable<int> IDClient
		{
			get
			{
				return this._IDClient;
			}
			set
			{
				if ((this._IDClient != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDClientChanging(value);
					this.SendPropertyChanging();
					this._IDClient = value;
					this.SendPropertyChanged("IDClient");
					this.OnIDClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAngajat", DbType="Int")]
		public System.Nullable<int> IDAngajat
		{
			get
			{
				return this._IDAngajat;
			}
			set
			{
				if ((this._IDAngajat != value))
				{
					if (this._Angajat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDAngajatChanging(value);
					this.SendPropertyChanging();
					this._IDAngajat = value;
					this.SendPropertyChanged("IDAngajat");
					this.OnIDAngajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMasa", DbType="Int")]
		public System.Nullable<int> IDMasa
		{
			get
			{
				return this._IDMasa;
			}
			set
			{
				if ((this._IDMasa != value))
				{
					if (this._Mese.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDMasaChanging(value);
					this.SendPropertyChanging();
					this._IDMasa = value;
					this.SendPropertyChanged("IDMasa");
					this.OnIDMasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRezervare", DbType="Date")]
		public System.Nullable<System.DateTime> DataRezervare
		{
			get
			{
				return this._DataRezervare;
			}
			set
			{
				if ((this._DataRezervare != value))
				{
					this.OnDataRezervareChanging(value);
					this.SendPropertyChanging();
					this._DataRezervare = value;
					this.SendPropertyChanged("DataRezervare");
					this.OnDataRezervareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrLocuri", DbType="Int")]
		public System.Nullable<int> NrLocuri
		{
			get
			{
				return this._NrLocuri;
			}
			set
			{
				if ((this._NrLocuri != value))
				{
					this.OnNrLocuriChanging(value);
					this.SendPropertyChanging();
					this._NrLocuri = value;
					this.SendPropertyChanged("NrLocuri");
					this.OnNrLocuriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora", DbType="NVarChar(6)")]
		public string Ora
		{
			get
			{
				return this._Ora;
			}
			set
			{
				if ((this._Ora != value))
				{
					this.OnOraChanging(value);
					this.SendPropertyChanging();
					this._Ora = value;
					this.SendPropertyChanged("Ora");
					this.OnOraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajat_Rezervari", Storage="_Angajat", ThisKey="IDAngajat", OtherKey="IDAngajat", IsForeignKey=true)]
		public Angajat Angajat
		{
			get
			{
				return this._Angajat.Entity;
			}
			set
			{
				Angajat previousValue = this._Angajat.Entity;
				if (((previousValue != value) 
							|| (this._Angajat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Angajat.Entity = null;
						previousValue.Rezervaris.Remove(this);
					}
					this._Angajat.Entity = value;
					if ((value != null))
					{
						value.Rezervaris.Add(this);
						this._IDAngajat = value.IDAngajat;
					}
					else
					{
						this._IDAngajat = default(Nullable<int>);
					}
					this.SendPropertyChanged("Angajat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mese_Rezervari", Storage="_Mese", ThisKey="IDMasa", OtherKey="IDMasa", IsForeignKey=true)]
		public Mese Mese
		{
			get
			{
				return this._Mese.Entity;
			}
			set
			{
				Mese previousValue = this._Mese.Entity;
				if (((previousValue != value) 
							|| (this._Mese.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mese.Entity = null;
						previousValue.Rezervaris.Remove(this);
					}
					this._Mese.Entity = value;
					if ((value != null))
					{
						value.Rezervaris.Add(this);
						this._IDMasa = value.IDMasa;
					}
					else
					{
						this._IDMasa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Mese");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Rezervari", Storage="_Client", ThisKey="IDClient", OtherKey="IDClient", IsForeignKey=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.Rezervaris.Remove(this);
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.Rezervaris.Add(this);
						this._IDClient = value.IDClient;
					}
					else
					{
						this._IDClient = default(Nullable<int>);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Client")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDClient;
		
		private string _Nume;
		
		private string _Prenume;
		
		private System.Nullable<System.DateTime> _DataNastere;
		
		private string _Username;
		
		private string _Email;
		
		private string _Parola;
		
		private System.Nullable<int> _Puncte;
		
		private EntitySet<Comenzi> _Comenzis;
		
		private EntitySet<Rezervari> _Rezervaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDClientChanging(int value);
    partial void OnIDClientChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnDataNastereChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNastereChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnParolaChanging(string value);
    partial void OnParolaChanged();
    partial void OnPuncteChanging(System.Nullable<int> value);
    partial void OnPuncteChanged();
    #endregion
		
		public Client()
		{
			this._Comenzis = new EntitySet<Comenzi>(new Action<Comenzi>(this.attach_Comenzis), new Action<Comenzi>(this.detach_Comenzis));
			this._Rezervaris = new EntitySet<Rezervari>(new Action<Rezervari>(this.attach_Rezervaris), new Action<Rezervari>(this.detach_Rezervaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDClient", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDClient
		{
			get
			{
				return this._IDClient;
			}
			set
			{
				if ((this._IDClient != value))
				{
					this.OnIDClientChanging(value);
					this.SendPropertyChanging();
					this._IDClient = value;
					this.SendPropertyChanged("IDClient");
					this.OnIDClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNastere", DbType="Date")]
		public System.Nullable<System.DateTime> DataNastere
		{
			get
			{
				return this._DataNastere;
			}
			set
			{
				if ((this._DataNastere != value))
				{
					this.OnDataNastereChanging(value);
					this.SendPropertyChanging();
					this._DataNastere = value;
					this.SendPropertyChanged("DataNastere");
					this.OnDataNastereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(20)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parola", DbType="VarChar(517)")]
		public string Parola
		{
			get
			{
				return this._Parola;
			}
			set
			{
				if ((this._Parola != value))
				{
					this.OnParolaChanging(value);
					this.SendPropertyChanging();
					this._Parola = value;
					this.SendPropertyChanged("Parola");
					this.OnParolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puncte", DbType="Int")]
		public System.Nullable<int> Puncte
		{
			get
			{
				return this._Puncte;
			}
			set
			{
				if ((this._Puncte != value))
				{
					this.OnPuncteChanging(value);
					this.SendPropertyChanging();
					this._Puncte = value;
					this.SendPropertyChanged("Puncte");
					this.OnPuncteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Comenzi", Storage="_Comenzis", ThisKey="IDClient", OtherKey="IDClient")]
		public EntitySet<Comenzi> Comenzis
		{
			get
			{
				return this._Comenzis;
			}
			set
			{
				this._Comenzis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Rezervari", Storage="_Rezervaris", ThisKey="IDClient", OtherKey="IDClient")]
		public EntitySet<Rezervari> Rezervaris
		{
			get
			{
				return this._Rezervaris;
			}
			set
			{
				this._Rezervaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comenzis(Comenzi entity)
		{
			this.SendPropertyChanging();
			entity.Client = this;
		}
		
		private void detach_Comenzis(Comenzi entity)
		{
			this.SendPropertyChanging();
			entity.Client = null;
		}
		
		private void attach_Rezervaris(Rezervari entity)
		{
			this.SendPropertyChanging();
			entity.Client = this;
		}
		
		private void detach_Rezervaris(Rezervari entity)
		{
			this.SendPropertyChanging();
			entity.Client = null;
		}
	}
	
	public partial class GetClientNameByOrderIdResult
	{
		
		private string _Nume;
		
		private string _Prenume;
		
		public GetClientNameByOrderIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this._Nume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this._Prenume = value;
				}
			}
		}
	}
	
	public partial class GetClientNameByReservationIdResult
	{
		
		private string _Nume;
		
		private string _Prenume;
		
		public GetClientNameByReservationIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this._Nume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this._Prenume = value;
				}
			}
		}
	}
	
	public partial class GetEmployeeIdByEmailResult
	{
		
		private int _IDAngajat;
		
		public GetEmployeeIdByEmailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAngajat", DbType="Int NOT NULL")]
		public int IDAngajat
		{
			get
			{
				return this._IDAngajat;
			}
			set
			{
				if ((this._IDAngajat != value))
				{
					this._IDAngajat = value;
				}
			}
		}
	}
	
	public partial class GetNrLocuriByIdRezervareResult
	{
		
		private System.Nullable<int> _NrLocuri;
		
		public GetNrLocuriByIdRezervareResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrLocuri", DbType="Int")]
		public System.Nullable<int> NrLocuri
		{
			get
			{
				return this._NrLocuri;
			}
			set
			{
				if ((this._NrLocuri != value))
				{
					this._NrLocuri = value;
				}
			}
		}
	}
	
	public partial class GetNumeByEmailResult
	{
		
		private string _Nume;
		
		public GetNumeByEmailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this._Nume = value;
				}
			}
		}
	}
	
	public partial class GetNumePrenumeByEmailResult
	{
		
		private string _Nume;
		
		private string _Prenume;
		
		public GetNumePrenumeByEmailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this._Nume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this._Prenume = value;
				}
			}
		}
	}
	
	public partial class GetPrenumeByEmailResult
	{
		
		private string _Prenume;
		
		public GetPrenumeByEmailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this._Prenume = value;
				}
			}
		}
	}
	
	public partial class GetRolByEmailResult
	{
		
		private string _Rol;
		
		public GetRolByEmailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="NVarChar(8)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
